from flask import Flask, request, jsonify
from flask_cors import CORS
from dotenv import load_dotenv
from email.message import EmailMessage
from datetime import datetime
import smtplib
import os
import traceback

# Load environment variables
load_dotenv()

app = Flask(__name__)

# Allow requests from the deployed React frontend
CORS(
    app,
    resources={
        r"/api/*": {
            "origins": [
                "https://tech-ascent-zera.vercel.app"
            ]
        }
    }
)

# Gmail credentials
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")

# Safe configuration check
print("EMAIL_USER configured:", bool(EMAIL_USER))
print("EMAIL_PASS configured:", bool(EMAIL_PASS))


@app.route("/", methods=["GET"])
def home():
    return jsonify({
        "message": "ZERA Flask Backend is running successfully."
    })


@app.route("/api/contact", methods=["POST"])
def receive_contact():
    try:
        data = request.get_json()

        # Get submitted chatbot details
        name = data.get("name", "").strip()
        age = data.get("age", "").strip()
        location = data.get("location", "").strip()
        email = data.get("email", "").strip()
        grievance = data.get("grievance", "").strip()

        # Validate required fields
        if not all([name, age, location, email, grievance]):
            return jsonify({
                "success": False,
                "message": "All fields are required."
            }), 400

        # Check credentials before attempting to send
        if not EMAIL_USER or not EMAIL_PASS:
            raise ValueError("EMAIL_USER or EMAIL_PASS is not configured.")

        # Current date and time
        submitted_at = datetime.now().strftime("%d %B %Y, %I:%M %p")

        # Create email
        message = EmailMessage()

        message["Subject"] = f"New Request Received from {name}"
        message["From"] = EMAIL_USER
        message["To"] = EMAIL_USER
        message["Reply-To"] = email

        message.set_content(f"""
ZERA - Guardian of the Unheard

A new request has been submitted through the website.

Visitor Details
----------------
Name: {name}
Age: {age}
Location: {location}
Email: {email}

Grievance / Request
-------------------
{grievance}

Date and Time
-------------
{submitted_at}

This message was automatically generated by the ZERA website.
""")

        # Send email through Gmail SMTP
with smtplib.SMTP("smtp.gmail.com", 587, timeout=20) as smtp:
    smtp.ehlo()
    smtp.starttls()
    smtp.ehlo()
    smtp.login(EMAIL_USER, EMAIL_PASS)
    smtp.send_message(message)
        return jsonify({
            "success": True,
            "message": "Request submitted successfully."
        }), 200

    except Exception as error:
    import traceback

    print("EMAIL ERROR:", repr(error))
    traceback.print_exc()

    return jsonify({
        "success": False,
        "message": "Unable to submit request."
    }), 500

if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))

    app.run(
        host="0.0.0.0",
        port=port,
        debug=False
    )